# GitHub Pages configuration for Nihon Dojo
# SEO optimization and site configuration

# Site settings
title: Nihon Dojo - Japanese Learning for Adults Who Want Results
description: >-
  Japanese learning for adults who want results, not games. AI-powered sentence generation,
  FSRS spaced repetition, and formality switching. Two-year fluency guarantee or full refund.
  Available on iOS and Android.
url: "https://nihondojo.ai"
baseurl: ""

# SEO and social
twitter:
  username: nihondojoai
  card: summary_large_image

social:
  name: Nihon Dojo
  links:
    - https://twitter.com/nihondojoai

# GitHub Pages plugins for SEO
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Include these files in GitHub Pages build
include:
  - CNAME
  - robots.txt
  - sitemap.xml
  - manifest.json
  - humans.txt
  - ads.txt
  - security.txt
  - 404.html

# Exclude from processing
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - src
  - README.md
  - marketing.md 